// =================================================================================
// This is auto-generated by GoFrame CLI tools only once. Fill this file as you wish.
// =================================================================================

package agent
