// =================================================================================
// This file is auto-generated by the GoFrame CLI tools. You may modify it as needed.
// =================================================================================

package dao

import (
	"agent/internal/dao/internal"
)

// messagesDao is the data access object for the table messages.
// You can define custom methods on it to extend its functionality as needed.
type messagesDao struct {
	*internal.MessagesDao
}

var (
	// Messages is a globally accessible object for table messages operations.
	Messages = messagesDao{internal.NewMessagesDao()}
)

// Add your custom methods and functionality below.
