// =================================================================================
// This file is auto-generated by the GoFrame CLI tools. You may modify it as needed.
// =================================================================================

package dao

import (
	"agent/internal/dao/internal"
)

// sessionsDao is the data access object for the table sessions.
// You can define custom methods on it to extend its functionality as needed.
type sessionsDao struct {
	*internal.SessionsDao
}

var (
	// Sessions is a globally accessible object for table sessions operations.
	Sessions = sessionsDao{internal.NewSessionsDao()}
)

// Add your custom methods and functionality below.
